# Generated by Django 3.1 on 2020-09-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_offersad_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offersad',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
