# Generated by Django 3.1 on 2020-09-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_offersad_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offersad',
            name='image',
        ),
    ]
