# Generated by Django 3.1 on 2020-09-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20200908_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersad',
            name='category',
            field=models.CharField(choices=[('hotel', 'hotel'), ('food', 'food'), ('activities', 'activities'), ('clothing', 'clothing'), ('items', 'items'), ('other', 'other')], default='all', max_length=100, null=True),
        ),
    ]
