# Generated by Django 3.1 on 2020-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_auto_20200908_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersad',
            name='category',
            field=models.CharField(choices=[(0, 'all'), ('hotel', 'hotel'), ('food', 'food'), ('activities', 'activities'), ('clothing', 'clothing'), ('items', 'items'), ('other', 'other')], default=0, max_length=100, null=True),
        ),
    ]
