# Generated by Django 3.1 on 2020-09-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20200908_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersad',
            name='contact_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='offersad',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
